dist: trusty
language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: build
      script: ./gradlew assemble
    - stage: unit test
      script: ./gradlew :cleanJvmTest :jvmTest --tests "com.vbytsyuk.pomodoro.*"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify